/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Map.map;
import java.awt.Color;
import java.util.Arrays;

/**
 *
 * @author rajazulqarnain
 */
public class GUI extends javax.swing.JDialog {

    /**
     * Creates new form GUII
     */
    
    public GUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        YU = new javax.swing.JTextField();
        NT = new javax.swing.JTextField();
        BC = new javax.swing.JTextField();
        AL = new javax.swing.JTextField();
        SK = new javax.swing.JTextField();
        MB = new javax.swing.JTextField();
        ON = new javax.swing.JTextField();
        QC = new javax.swing.JTextField();
        NF = new javax.swing.JTextField();
        NB = new javax.swing.JTextField();
        NS = new javax.swing.JTextField();
        Algorithm_button = new javax.swing.JButton();
        NU = new javax.swing.JTextField();
        PE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        YU.setEditable(false);
        YU.setText(" Yukon");

        NT.setEditable(false);
        NT.setText("                Northwest Territories");

        BC.setEditable(false);
        BC.setText("British Columbia");

        AL.setEditable(false);
        AL.setText("     Alberta");

        SK.setEditable(false);
        SK.setText("Saskatchewan");
        SK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SKActionPerformed(evt);
            }
        });

        MB.setEditable(false);
        MB.setText("   Manitoba");

        ON.setEditable(false);
        ON.setText("    Ontario");

        QC.setEditable(false);
        QC.setText("    Quebec");

        NF.setEditable(false);
        NF.setText("     Newfoundland");

        NB.setEditable(false);
        NB.setText("New Brunswick");

        NS.setEditable(false);
        NS.setText("Nova Scotia");

        Algorithm_button.setText("Run CSP Algorithm");
        Algorithm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Algorithm_buttonActionPerformed(evt);
            }
        });

        NU.setEditable(false);
        NU.setText("    Nunavut");

        PE.setEditable(false);
        PE.setText("Prince Edward Island");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/MAP.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(YU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NT))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BC, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SK, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NU)
                    .addComponent(MB, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ON, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(NS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(QC, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(PE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 85, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(NF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Algorithm_button, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(NF, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(NT, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BC)
                                .addComponent(AL)
                                .addComponent(SK)
                                .addComponent(MB, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NB, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(QC, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PE, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NS, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9))
                    .addComponent(ON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Algorithm_button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SKActionPerformed

    private void Algorithm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Algorithm_buttonActionPerformed
        // TODO add your handling code here:
        System.out.println("CSP Canadian Map Coloring"); 
                Map.map Graph = new map(); 
		Graph.ProvinceLink(0, 1); 
		Graph.ProvinceLink(0, 2); 
		Graph.ProvinceLink(1, 0); 
		Graph.ProvinceLink(1, 2); 
                Graph.ProvinceLink(1, 3);
		Graph.ProvinceLink(2, 0); 
		Graph.ProvinceLink(2, 1);
                Graph.ProvinceLink(2, 3);
                Graph.ProvinceLink(2, 4);
                Graph.ProvinceLink(2, 5);
                Graph.ProvinceLink(3, 2);
                Graph.ProvinceLink(3, 5);
                Graph.ProvinceLink(4, 2);
                Graph.ProvinceLink(4, 6);
                Graph.ProvinceLink(5, 2);
                Graph.ProvinceLink(5, 3);
                Graph.ProvinceLink(5, 6);
                Graph.ProvinceLink(6, 4);
                Graph.ProvinceLink(6, 5);
                Graph.ProvinceLink(6, 7);
                Graph.ProvinceLink(7, 6);
                Graph.ProvinceLink(7, 8);
                Graph.ProvinceLink(8, 7);
                Graph.ProvinceLink(8, 9);
                Graph.ProvinceLink(8, 10);
                Graph.ProvinceLink(9, 8);
                Graph.ProvinceLink(9, 11);
                Graph.ProvinceLink(10, 8);
                Graph.ProvinceLink(11, 9);
                Graph.CSPMap();
                Map.map newArray = new map();
        
         int a;
         map obj= new map();
         if(obj.AssignColor.length == obj.Vertex){
             NU.setBackground(Color.red);
             NT.setBackground(Color.GREEN);
             YU.setBackground(Color.red);
             BC.setBackground(Color.YELLOW);
             AL.setBackground(Color.red);
             SK.setBackground(Color.YELLOW);
             MB.setBackground(Color.GREEN);
             ON.setBackground(Color.red);
             QC.setBackground(Color.YELLOW);
             NS.setBackground(Color.YELLOW);
             NB.setBackground(Color.red);
             NF.setBackground(Color.red);
             PE.setBackground(Color.red);
             System.out.println(Arrays.toString(obj.CanPro));
            // List2.setText(Arrays.toString(obj.Province));
            //TextArea1.setText(Graph.CSPMap());
         }
         for (int i = 0; i < 13; i++) {
           a = obj.AssignColor[i];
             //System.out.println(obj.toString());
        }
         //a = obj.arr[0];
         //System.out.println(a);
        
    }//GEN-LAST:event_Algorithm_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI dialog = new GUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AL;
    private javax.swing.JButton Algorithm_button;
    private javax.swing.JTextField BC;
    private javax.swing.JTextField MB;
    private javax.swing.JTextField NB;
    private javax.swing.JTextField NF;
    private javax.swing.JTextField NS;
    private javax.swing.JTextField NT;
    private javax.swing.JTextField NU;
    private javax.swing.JTextField ON;
    private javax.swing.JTextField PE;
    private javax.swing.JTextField QC;
    private javax.swing.JTextField SK;
    private javax.swing.JTextField YU;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}

/*
References:
Greeks for Greeks / Languages Java "Analysis of Basic Algorithm".
JavaTpoint.com
W3school.com/java
*/
